# Generated by Django 4.1.7 on 2023-10-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_log.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'School log',
                'verbose_name_plural': 'School logs',
                'ordering': ['-published'],
            },
        ),
    ]
